<?php
/**
 * Flagbit_Faq
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the H&O Commercial License
 * that is bundled with this package in the file LICENSE_HO.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.h-o.nl/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@h-o.com so we can send you a copy immediately.
 *
 * @category    Flagbit
 * @package     Flagbit_Faq
 * @copyright   Copyright © 2013 H&O (http://www.h-o.nl/)
 * @license     H&O Commercial License (http://www.h-o.nl/license)
 * @author      Paul Hachmang – H&O <info@h-o.nl>
 *
 * 
 */

/** @var $this Flagbit_Faq_Block_Frontend_List_Widget */
?>
<?php if ($this->getFaqCollection()->count()): ?>
<dl class="faq-items">
    <?php /** @var $faqItem Flagbit_Faq_Model_Faq */ ?>
    <?php foreach ($this->getFaqCollection() as $faqItem): ?>
    <dt id="faq-item-<?php echo $faqItem->getId() ?>">
        <?php echo $this->htmlEscape($faqItem->getQuestion()) ?>
    </dt>
    <dd>
        <?php echo $this->getAnswerHtml($faqItem); ?>
    </dd>
    <?php endforeach; ?>
</dl>
<?php else: ?>
<p class="faq-items"><?php echo $this->__('There are no FAQ items at the moment.') ?></p>
<?php endif; ?>
