<?php if ($_category = $this->getCategory()): ?>
<div>
	<h1><?php echo $this->htmlEscape($_category->getCategoryName()) ?> <a href='/faqs/' class='inherit'><small>(Frequently Asked Questions)</small></a></h1>
</div>

<div class="faq-category">
	<dl class="faq-items">
		<?php foreach ($this->getItemCollectionByCategory($_category) as $faqItem): ?>
		<dt id="faq-item-<?php echo $faqItem->getId() ?>" class='faq-question' data-id="<?php echo $faqItem->getId() ?>">
			<?php echo $this->htmlEscape($faqItem->getQuestion()) ?>
		</dt>
		<dd class='faq-answer'>
			<?php echo ($faqItem->getAnswerHtml() ? $faqItem->getAnswer() : '<p>' . implode('</p><p>', explode("\n", $this->htmlEscape($faqItem->getAnswer()))) . '</p>') ?>
		</dd>
		<?php endforeach; ?>
	</dl>
</div>
	
<a href="<?php echo Mage :: app()->getStore()->getUrl('faq') ?>" title="<?php echo $this->__('Back to the FAQ home') ?>" class='back'><?php echo $this->__('Back to the FAQ home') ?></a>
</div>

<?php else: ?>
<div class="page-title">
	<h1><?php echo $this->__('Error') ?></h1>
</div>
	
<p><?php echo $this->__('The requested FAQ item could not be found!') ?></p>
<?php endif; ?>
